[package]
name = "bsoap"
version = "1.0.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["blocking", "json", "rustls-tls"] }
yaserde = "0.12.0"
yaserde_derive = "0.12.0"
serde = { version = "1.0.219", features = ["derive"] }